<?php

$_COS_LANG_MODULE['Sort menu'] = 'Sorter menu';
$_COS_LANG_MODULE['Saving item ... '] = 'Gemmer menu ... ';
$_COS_LANG_MODULE['Click to edit'] = 'Tryk og ret menu titel';
$_COS_LANG_MODULE['Click on the menu items and edit them. Empty will delete'] = 'Tryk på menu titler og ændr dem - slet ved at gemme som tomme';
$_COS_LANG_MODULE['Menu has been reset'] = 'Opdatering fuldført';
$_COS_LANG_MODULE['Confirm reset'] = 'Reset menuer til oprindeligt tilstand';
$_COS_LANG_MODULE['Menu item deleted'] = 'Menu punkt er fjernet';
$_COS_LANG_MODULE['Pick menu section'] = 'Vælg menu sektion';
