<?php

$_COS_LANG_MODULE = array();

$_COS_LANG_MODULE['menus_filter'] = 'Vælg menu sektion';
$_COS_LANG_MODULE['menus_menu_item_removed'] = 'Menu punkt er fjernet';
$_COS_LANG_MODULE['menus_reset_done'] = 'Opdatering fuldført';
$_COS_LANG_MODULE['menus_confirm_reset'] = 'Reset menuer til oprindeligt tilstand';
$_COS_LANG_MODULE['menus_edit_indicator'] = 'Gemmer menu ... ';
$_COS_LANG_MODULE['menus_edit_tooltip'] = 'Tryk og ret menu titel';
$_COS_LANG_MODULE['menus_menu_edit_help'] = 'Tryk på menu titler og ændr dem - slet ved at gemme som tomme';
