<?php


// Translation of file /modules/menus/module.php

$_COS_LANG_MODULE['Pick menu section'] = 'Vælg menu sektion';

// Translation of file /modules/menus/reset.php

$_COS_LANG_MODULE['Menu has been reset'] = 'Opdatering fuldført';
$_COS_LANG_MODULE['Confirm reset'] = 'Reset menuer til oprindeligt tilstand';

// Translation of file /modules/menus/menu_update.php

$_COS_LANG_MODULE['Menu item deleted'] = 'Menu punkt er fjernet';

// Translation of file /modules/menus/edit.php

$_COS_LANG_MODULE['Saving item ... '] = 'Gemmer menu ... ';
$_COS_LANG_MODULE['Click to edit'] = 'Tryk og ret menu titel';
$_COS_LANG_MODULE['Click on the menu items and edit them. Empty will delete'] = 'Tryk på menu titler og ændr dem - slet ved at gemme som tomme';

// Translation of file /modules/menus/index.php

$_COS_LANG_MODULE['Sort menu'] = 'Sorter menu';
