<?php

$_COS_LANG_MODULE['Menu item deleted'] = '菜单项删除';
$_COS_LANG_MODULE['Sort menu'] = '排序菜单';
$_COS_LANG_MODULE['Saving item ... '] = '节能项目...';
$_COS_LANG_MODULE['Click to edit'] = '点击编辑';
$_COS_LANG_MODULE['Click on the menu items and edit them. Empty will delete'] = '点击菜单项和编辑它们。空将删除';
$_COS_LANG_MODULE['Pick menu section'] = '挑选菜单部分';
$_COS_LANG_MODULE['Menu has been reset'] = '菜单被重置';
$_COS_LANG_MODULE['Confirm reset'] = '确认复位';
