<?php


// Translation of file /modules/menus/menu_update.php

$_COS_LANG_MODULE['Menu item deleted'] = 'Menu item deleted';

// Translation of file /modules/menus/index.php

$_COS_LANG_MODULE['Sort menu'] = 'Sort menu';

// Translation of file /modules/menus/edit.php

$_COS_LANG_MODULE['Saving item ... '] = 'Saving item ... ';
$_COS_LANG_MODULE['Click to edit'] = 'Click to edit';
$_COS_LANG_MODULE['Click on the menu items and edit them. Empty will delete'] = 'Click on the menu items and edit them. Empty will delete';

// Translation of file /modules/menus/module.php

$_COS_LANG_MODULE['Pick menu section'] = 'Pick menu section';

// Translation of file /modules/menus/reset.php

$_COS_LANG_MODULE['Menu has been reset'] = 'Menu has been reset';
$_COS_LANG_MODULE['Confirm reset'] = 'Confirm reset';
