<?php

$_COS_LANG_MODULE = array();

$_COS_LANG_MODULE['menus_filter'] = 'Pick menu section';
$_COS_LANG_MODULE['menus_menu_item_removed'] = 'Menu item deleted';
$_COS_LANG_MODULE['menus_edit_indicator'] = 'Saving item ... ';
$_COS_LANG_MODULE['menus_edit_tooltip'] = 'Click to edit';
$_COS_LANG_MODULE['menus_menu_edit_help'] = 'Click on the menu items and edit them. Empty will delete';

$_COS_LANG_MODULE['menus_reset_done'] = 'Menu has been reset';
$_COS_LANG_MODULE['menus_confirm_reset'] = 'Confirm reset';
