<?php

$_COS_LANG_MODULE['Pick menu section'] = 'Pick menu section';
$_COS_LANG_MODULE['Menu item deleted'] = 'Menu item deleted';
$_COS_LANG_MODULE['Saving item ... '] = 'Saving item ... ';
$_COS_LANG_MODULE['Click to edit'] = 'Click to edit';
$_COS_LANG_MODULE['Click on the menu items and edit them. Empty will delete'] = 'Click on the menu items and edit them. Empty will delete';
$_COS_LANG_MODULE['Menu has been reset'] = 'Menu has been reset';
$_COS_LANG_MODULE['Confirm reset'] = 'Confirm reset';
