<?php

$_COS_LANG_MODULE['Pick menu section'] = 'Velg seksjon';
$_COS_LANG_MODULE['Menu item deleted'] = 'Menyvalget er fjernet';
$_COS_LANG_MODULE['Saving item ... '] = 'Sparer menyen ...';
$_COS_LANG_MODULE['Click to edit'] = 'Trykk og høyre meny tittel';
$_COS_LANG_MODULE['Click on the menu items and edit them. Empty will delete'] = 'Trykk på MENU-titler og endre dem - slette, lagre som tom';
$_COS_LANG_MODULE['Menu has been reset'] = 'Oppdater fullføre';
$_COS_LANG_MODULE['Confirm reset'] = 'Tilbakestille menyene til opprinnelig tilstand';
