<?php

/**
 * @ignore
 */

$_MODULE_MENU = array (
    array(
        'title' => lang::translate('menus_menu_sort'),
        'url' => '/menus/index',
        'auth' => 'admin'
    ),
    
    array(
        'title' => lang::translate('menus_menu_edit'),
        'url' => '/menus/edit',
        'auth' => 'admin'
    ),
    
    array(
        'title' => lang::translate('menus_menu_reset'),
        'url' => '/menus/reset',
        'auth' => 'admin'
    ),

);
 