<?php

$_COS_LANG_MODULE['Pick menu section'] = 'Wählen Sie im Menübereich';
$_COS_LANG_MODULE['Menu has been reset'] = 'Menü wurde zurückgesetzt';
$_COS_LANG_MODULE['Confirm reset'] = 'Zurücksetzen zu bestätigen';
$_COS_LANG_MODULE['Menu item deleted'] = 'Menüpunkt gelöscht';
$_COS_LANG_MODULE['Saving item ... '] = 'Speichern Artikel ...';
$_COS_LANG_MODULE['Click to edit'] = 'Klicken bearbeiten';
$_COS_LANG_MODULE['Click on the menu items and edit them. Empty will delete'] = 'Klicken Sie auf die Menüpunkte und bearbeiten. Leere löscht';
$_COS_LANG_MODULE['Sort menu'] = 'Menü Sortieren';
