<?php

$_COS_LANG_MODULE['Menu item deleted'] = 'Valikkokohta poistetaan';
$_COS_LANG_MODULE['Sort menu'] = 'Lajittelu-';
$_COS_LANG_MODULE['Saving item ... '] = 'Säästää valikosta ...';
$_COS_LANG_MODULE['Click to edit'] = 'Paina ja oikean valikon otsikko';
$_COS_LANG_MODULE['Click on the menu items and edit them. Empty will delete'] = 'Paina valikossa otsikot ja muuttaa niitä - poistaa, jollei tyhjä';
$_COS_LANG_MODULE['Pick menu section'] = 'Valitse valikosta kohta';
$_COS_LANG_MODULE['Menu has been reset'] = 'Päivitä loppuun';
$_COS_LANG_MODULE['Confirm reset'] = 'Nollaa valikot alkuperäiseen tilaan';
