<?php

$_COS_LANG_MODULE['Menu item deleted'] = 'Menyalternativ utgår';
$_COS_LANG_MODULE['Sort menu'] = 'Sortera-menyn';
$_COS_LANG_MODULE['Saving item ... '] = 'Spara objekt ...';
$_COS_LANG_MODULE['Click to edit'] = 'Klicka för att redigera';
$_COS_LANG_MODULE['Click on the menu items and edit them. Empty will delete'] = 'Klicka på menyalternativen och redigera dem. Tom kommer att raderas';
$_COS_LANG_MODULE['Pick menu section'] = 'Välj menyn avsnittet';
$_COS_LANG_MODULE['Menu has been reset'] = 'Menyn har återställs varit';
$_COS_LANG_MODULE['Confirm reset'] = 'Bekräfta återställning';
