<?php

$_COS_LANG_MODULE['menus_filter'] = 'Välj menyn avsnittet';
$_COS_LANG_MODULE['menus_menu_item_removed'] = 'Menyalternativ utgår';
$_COS_LANG_MODULE['menus_edit_indicator'] = 'Spara objekt ...';
$_COS_LANG_MODULE['menus_edit_tooltip'] = 'Klicka för att redigera';
$_COS_LANG_MODULE['menus_menu_edit_help'] = 'Klicka på menyalternativen och redigera dem. Tom kommer att raderas';
$_COS_LANG_MODULE['menus_reset_done'] = 'Menyn har återställs varit';
$_COS_LANG_MODULE['menus_confirm_reset'] = 'Bekräfta återställning';
